### ISSUE TITLE
Pedestrian get stucked before entering channel

### ISSUE THREAD

**Issue by bcoueraud87** [JuPedSim/jpscore#1044]
**JuPedSim - JPScore**

- Current date   : 27/09/2022
- Version        : dev
- Compiler       : MSVC
- Commit hash    :
- Commit date    :
- Branch         : SUMO-integration
- Python         :

**Description of the bug**
In the case of a simple geometry with a channel inserted in between two bigger rooms, the pedestrian gets stucked into one corner before entering the channel. 

**Expected behavior**
The channel has a width of 3m, so the pedestrian should be able to enter and walks his/her way out of the channel.

**Screenshots**
![bug1](https://user-images.githubusercontent.com/56519579/192512748-46dcdc2c-c710-4cc5-88e8-b5c62b5acb62.png)

**Additional context**
Here is the [geometry](https://github.com/JuPedSim/jpscore/files/9654926/geometry.txt) and the [trajectory](https://github.com/JuPedSim/jpscore/files/9654930/trajectory.txt) which can be visualized with this [script](https://github.com/JuPedSim/jpscore/files/9654942/vis.txt).

**Comment by chraibi** [comment]
To which points does the goal of the agent point to?

**Comment by bcoueraud87** [comment]
The agent should finish its journey at the end of the room right after the channel. Concretly, in the coordinate system that we use, it is the point (299.9, 0).

**Comment by Ozaq** [comment]
After looking into this I can see that the navigation graph is not constructed correctly.

In the picture below you see the portal edges (edges between the to-be-traversed triangles). The image contains the following errors:
* A boundary edge is selected as portal edge, this is incorrect because a portal edge has to be an edge shared between to adjacent triangels
* A portal edge that should have been selected is not selected
* A portal edge is selected twice (notice the different draw pattern of the green line of the center portal)

<img width="2323" alt="portal_edges" src="https://user-images.githubusercontent.com/13482142/192742535-87a75cee-d96b-4fad-b78e-26b78f6b1a29.png">

Im inclined to first make all these internals accessible from python to ease future debugging although I do not want this to become part of the public api.

**Comment by Ozaq** [comment]
@bcoueraud87 this should be fixed on SUMO-Integration, can you please verify.

**Comment by bcoueraud87** [comment]
@Ozaq I confirm that the problem has been solved, thank you. I propose to close this ticket.
