### ISSUE TITLE
Remove xsd Files. 

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#436]
**Is your feature request related to a problem? Please describe.**
We have some `xsd` files, however, there are not up to date. 

Unless we can find an easy way to validate our XML files using these XSD files, I don't see the point in keeping them around. 

Any ideas?

**Comment by Ozaq** [comment]
XSD files are the specs for your XML files and as such are invaluable information when trying to parse or generate those XML files. I would suggest to update them and move from tinyxml to xerceces (https://xerces.apache.org/xerces-c/) Xerxes has a build in validation ox XML files versus their XSD. If I remember correctly the generated error messages are solid and allow the creator of an XML file to quickly pinpoint the error, e.g. missed an required attribute, supplied a double where an int was required etc...

This would greatly simplify the parsing code since a lot less manual error checking would be necessary.

**Comment by Ozaq** [comment]
Looking trough the issues its things like #382  #161 that probably would be a lot less hassle if xml validation with the accompanying xsd was used.

**Comment by chraibi** [comment]
I'm with you that validating of xml files with xsd will save us a lot of trouble. 
I'll have a look at xerces. It looks like it can do what we want..

**Comment by Ozaq** [comment]
I worked some with Xerxes in the past and it was pretty good, but i think migration would be a significant effort due to the difference in API. Still worth it though imo.

**Comment by zeroset** [comment]
We will not have an XSD validating XML parser. We should delete all xsd files and remove them from the xml files.

**Comment by chraibi** [comment]
no objetcions
