### ISSUE TITLE
Flow through bottlenecks

### ISSUE THREAD

**Issue by gjaeger** [JuPedSim/jpscore#613]
**Input files:**
* [ini_UO_300-300-080_om_3.xml](https://github.com/JuPedSim/jpscore/files/3967949/ini_UO_300-300-080_om_3.xml.zip)
* [geo_UO_300-300-080_jpscore.xml](https://github.com/JuPedSim/jpscore/files/3967950/geo_UO_300-300-080_jpscore.xml.zip)

**Observation**
In front of the bottleneck an unnatural congestion occurs near the walls.

**Screenshots**

![tmp_0000333](https://user-images.githubusercontent.com/7759675/70908677-068fb880-200c-11ea-93df-e6a1a5533d16.png)

video: [UO_300-300-080_om_3.mp4 (zip)](https://github.com/JuPedSim/jpscore/files/3968067/UO_300-300-080_om_3.mp4.zip)

**Comment by chraibi** [comment]
The phenomenon you observe here is due to a high value of the parameter `a` in the repulsive function `R` (see [Fig. 2, right](https://arxiv.org/abs/1512.05597)). 
In the original model, this value is equal to 5 and in the [generalized version](https://arxiv.org/abs/1908.10304) it is 3.

This parameter, and probably the others as well, are geometry dependent. 

The elongated nature of the corridor in front of the final bottleneck seems to promote
this phenomenon since pedestrians get pushed aside and are stuck on the walls; something we don't observe in the original and in the generalized model 

<img width="547" alt="Screenshot 2019-12-16 21 46 20" src="https://user-images.githubusercontent.com/5772973/70942427-f220df80-204e-11ea-9572-977f0ef8fc36.png">

[Fig. 14](https://arxiv.org/abs/1908.10304)

----

I suggest that you reduce the value of `a` (probably 1 or 2) and have another try. 
It is also worth trying to use these parameters after  

```
<exit_crossing_strategy>8</exit_crossing_strategy>
<wall_avoid_distance>0.8</wall_avoid_distance>
<use_wall_avoidance>true</use_wall_avoidance>
```
This will make the floor field show a wall-repulsive character, directing agents away from the wall

Here are some results of the simulation with a reduced `a`:

<img width="199" alt="Screenshot 2019-12-16 21 37 48" src="https://user-images.githubusercontent.com/5772973/70942853-dff37100-204f-11ea-8a12-7f52ef71b603.png">

<img width="155" alt="Screenshot 2019-12-16 21 37 55" src="https://user-images.githubusercontent.com/5772973/70942881-eeda2380-204f-11ea-9ad2-ca3d324f5fc5.png">
<img width="201" alt="Screenshot 2019-12-16 21 38 01" src="https://user-images.githubusercontent.com/5772973/70942884-eeda2380-204f-11ea-987b-4dd818a70d09.png">
<img width="195" alt="Screenshot 2019-12-16 21 38 08" src="https://user-images.githubusercontent.com/5772973/70942885-ef72ba00-204f-11ea-9cb1-abfd4bc1d209.png">

**Comment by chraibi** [comment]
@gjaeger if your question is answered, I suggest closing this issue.

To summarize I would say that the parameters for the simulation need proper calibration. 

The default values are not meant to be used in *all* scenarios. The user always needs to calibrate the model and try different outcomes.

**Comment by gjaeger** [comment]
I agree with you. We should take a closer look at the model calibration and explain the background.
