### ISSUE TITLE
Method A - different results for different path locations

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpscore#718]
In the dictionary you can finde two tests.
[jpsreport.zip](https://github.com/JuPedSim/jpscore/files/4305737/jpsreport.zip)

In Test-01 the report-ini is **not** located in the same dictionary as the geometry and the trajectory file. In Test-02 the report-ini is located in the same dictionary.
For Test-02 the analysis with report works fine and the output is saved as expected.
For Test-01 the analysis does not work as expected, the output-dictionaries have different names as in Test-02 and the Flow-NT-files are missing completely.

And for both tests, the log file was only written, if the output dictionary already exists.

**Comment by gjaeger** [comment]
@anna-braun I can confirm your observations with jpsreport _v0.8.4-928-g49c2c1d4-dirty_.

It looks like something is going wrong with `FD_FlowVelocity` in Method_A.cpp.

**Comment by anna-braun** [comment]
> @anna-braun I can confirm your observations with jpsreport _v0.8.4-928-g49c2c1d4-dirty_.
> 
> It looks like something is going wrong with `FD_FlowVelocity` in Method_A.cpp.

@gjaeger Yes it is the same with this / the newest version

**Comment by JetteSchumann** [comment]
@anna-braun since the name of the trajectory file is used when creating the outputfile names, the location of it must be defined separatly when it's not in the directory where jpsreport is executed.

`  <trajectories format="txt" unit="m">
    <file name="results/12-combine.txt" />
  </trajectories>
`
Should be:

`  <trajectories format="txt" unit="m">
    <file name="12-combine.txt" />
    <path location="results"/>
  </trajectories>`

This worked for me. Could you please try it?

Still working on the logging issue.

**Comment by gjaeger** [comment]
@JetteSchumann You are right. 

We should add a corresponding note in the section "[Trajectories](http://www.jupedsim.org/jpsreport_inifile.html#trajectories)". Like:

> *Note:* The separation of the sub-options `path` (location) and `file` (name) is necessary. The specification of an absolute or relative path in the `file` (name) option leads to an incorrect execution of the program. 

I've detected another problem with the logfile. No absolute or relative path may specified in the `<logfile>` option. Otherwise the logfile will not be created.

We should add a corresponding note in the section "[Logfile](http://www.jupedsim.org/jpsreport_inifile.html#logfile)". Like:

> *Note:* If an absolute or relative path is specified in the `logfile` option, no logfile is created.

**Comment by anna-braun** [comment]
> @anna-braun since the name of the trajectory file is used when creating the outputfile names, the location of it must be defined separatly when it's not in the directory where jpsreport is executed.
> 
> ` <trajectories format="txt" unit="m">`
> ` <file name="results/12-combine.txt" />`
> ` </trajectories>`
> 
> Should be:
> 
> ` <trajectories format="txt" unit="m">`
> ` <file name="12-combine.txt" />`
> ` <path location="results"/>`
> ` </trajectories>`
> 
> This worked for me. Could you please try it?
> 
> Still working on the logging issue.

@JetteSchumann 
Yes, this works for me. As Gregor says this should be adopted/changed in the docu.

**Comment by gjaeger** [comment]
Done with PR #726.
