### ISSUE TITLE
jpscore and jpsreport compile problem

### ISSUE THREAD

**Issue by Monk9636** [JuPedSim/jpscore#737]
When build solution of jpscore in visual studio 2019, skipped two project, one is jpsreport. and result show the jpscore works well but jpsreport don't work well. latest build encounter error code C1083, says "Cannot open include file: 'boost/polygon/voronoi': No such file or directory in jpsreport project ,the filepath is F:\shixiongchengxu\jpscore\jpsreport\general\Macros.h	line 34". former steps follows the guide "https://www.jupedsim.org/jupedsim_install_on_windows.html", and no error occurs. and i found  the voronoi.hpp locate in the path-"F:\shixiongchengxu\vcpkg\packages\boost-polygon_x64-windows\include\boost\polygon\voronoi.hpp".
what i really need is the jpsreport of jupedsim, so i hope this problems can get an answer.

**Comment by xuqiancheng** [comment]
Hello, @Monk9636.
If you follow the guide "https://www.jupedsim.org/jupedsim_install_on_windows.html" to build jpscore and jpsreport on your windows, you can get "**jpscore.exe**" and "**jpsreport.exe**" in folder "**.\jpscore\build\bin\Debug**" or "**.\jpscore\build\bin\Release**". 
Then you can use jpsreport to do what you want.
If you meet troubles during the process, you can provide more details here, and it would be better with some screenshot. I will try to help you.

**Comment by Monk9636** [comment]
thanks a lot, it seems i built the jpscore solution successfully, "jpscore.exe" and "jpsreport.exe" is founded in the bin folder ,and it work well with some demos ,but i want to make sure that the "package" and "install" project skipped during compilation does't matter?

**Comment by zeroset** [comment]
The Package target is only required for building installation packages and requires NSIS to be installed. The install target requires administration permission and only copies the binaries to the desired installation directories. I think both is not required if you want to work with jpsreport or jpscore. You are fine with compiling both and using the jpscore.exe or jpsreport.exe in you bin folder. 
As the issue seems to be solved with that i will close it. If you have further problems, don't hesitate to open a new issue. 
Best, David
