### ISSUE TITLE
Create "Development" page in documentation

### ISSUE THREAD

**Issue by JetteSchumann** [JuPedSim/jpscore#761]
Should contain information on:

- Tests
- Coding guidelines
- Algorithms
- Code structure
- ...

**Comment by chraibi** [comment]
Note: The navigation bar can have two levels only.
 
What do you think about this?



- Tests
   - jpsreport
   - rimea
   - juelich
   - ...
- Development
    - Contributing 
    - Coding guidelines
    - Code structure

**Comment by gjaeger** [comment]
Some links for inspiration (based on firemodels/fds). I like the documentation of this project. The structure could be a bit clearer. The structure of our website is already good. 

## Notes Getting Started
- > If you are new to the project, a good place to start is [Git Notes: Getting Started](https://github.com/firemodels/fds/wiki/Git-Notes-Getting-Started).

## Developing
- [Configuration Management](https://github.com/firemodels/fds/wiki/Configuration-Management)
- [Developer Commit Guidelines](https://github.com/firemodels/fds/wiki/Developer-Commit-Guidelines)
- [Daily Workflow](https://github.com/firemodels/fds/wiki/FDS-Daily-Workflow)

## Validation and Verification
> The FDS [Validation Process](https://github.com/firemodels/fds/wiki/FDS-Validation-Process) and FDS [Verification Process](https://github.com/firemodels/fds/wiki/FDS-Verification-Process) describe how one compiles the FDS Validation, Verification and User's Guides by running all the test cases and compiling the manuals.
> Details of how these cases are developed is given by the [Validation Case Setup](https://github.com/firemodels/fds/wiki/Validation-Case-Setup-Example) and the [Verification Case Setup](https://github.com/firemodels/fds/wiki/Verification-Case-Setup-Example)

**Comment by gjaeger** [comment]
> Note: The navigation bar can have two levels only.
> 
> What do you think about this?
> 
> * Tests
>   
>   * jpsreport
>   * rimea
>   * juelich
>   * ...
> * Development
>   
>   * Contributing
>   * Coding guidelines
>   * Code structure

I like Mohcine's proposal. For the tests, I would add a page on the basic structure of the test.

**Comment by Ozaq** [comment]
Extending the developer documentation is a very good thing! Although you kind of have some duplication going on at the moment: there is everything under doc and then there is the README which conveniently gets rendered in Gihub sort of as the landing page for this project.

The README and the doc overlap when it comes to development issues like building from sources. So there is now two places where this has to be maintained. Not so nice.

Some projects I have seen maintain the external or user only documentation via github pages (doc) while everything architecture & development related is maintained as markdown files in the repository. That way you clearly separate the two views on the project (user vs. contributor), which also makes it easier for authors of documentation because it is now immediately clear who your audience is when writing documentation.

Personally I also think it’s good to have all development related doc as markdown files close to the sources because that way I can easily read them in my editor when coding.

On the other hand however having everything in one place is also nice, esp. if you have some sort of “mixed” audience, e.g. students who are supposed to add code but might do so under more supervision or in a more limited context. That way you can provide documentation with a focus of specific extension tasks etc. Although I do not think this is a problem for JPS at this time.

So in any case please extend the doc (+100) but be weary of duplicated descriptions (README vs doc)

**Comment by chraibi** [comment]
Your concern about things being doubled is right. However, I don't understand what you mean with
> Personally I also think it’s good to have all development-related doc as markdown files close to the sources because that way I can easily read them in my editor when coding.

alls docs are already markdown files close to the source. Do you mean, the developement documentation (insallation, etc) should go to README and the user doc as it is in the github page?

**Comment by Ozaq** [comment]
@chraibi yes, having the contributing, build, development guidelines in the README is nice imo. But it’s just one way of doing things. I like this approach because the README is the first thing I see on github. Also if you look at the Postgres source code for example you will find in most folders a description of what the code in this folder does e.g. https://github.com/postgres/postgres/tree/master/src/backend/optimizer or https://github.com/postgres/postgres/tree/master/src/backend/access/gin
Also nice is that gihub will automatically render the README if you open the folder. This is a very developer centric way of doing things so this should be reserved for developer info.

In any case I think both ways are fine and have their merits.

**Comment by chraibi** [comment]
related to #693

**Comment by chraibi** [comment]
> Some links for inspiration (based on firemodels/fds). I like the documentation of this project. The structure could be a bit clearer. The structure of our website is already good.
